esphome:
  on_boot:
    - delay: 5s
    - lvgl.widget.hide: boot_screen
    - delay: 30s
    - script.execute: screen_light

lvgl:
  displays: [my_display]
  touchscreens: [my_touchscreen]

  pages:
    - id: main_page
      widgets: []
    - id: clock_page
      widgets: []

  top_layer:
    widgets:
      - obj:
          id: boot_screen
          x: 0
          y: 0
          width: 100%
          height: 100%
          bg_color: ${color_bg_dark}
          bg_opa: COVER
          radius: 0
          pad_all: 0
          border_width: 0
          widgets:
            - image:
                align: CENTER
                src: boot_logo
                y: -100
            - label:
                align: CENTER
                text: "Starte Display Version: ${version}"
                text_color: ${color_text_dark_primary}
                y: 10
            - spinner:
                align: CENTER
                y: 120
                height: 50
                width: 50
                spin_time: 1s
                arc_length: 60deg
                arc_width: 8
                indicator:
                  arc_color: ${color_primary}
                  arc_width: 8
          on_press:
            - lvgl.widget.hide: boot_screen