esphome:
  name: display
  friendly_name: Display
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
# - esphome platform: For OTA via ESPHome Dashboard
# - http_request platform: For managed firmware updates via manifest.json
ota:
  - platform: esphome
  - platform: http_request

# Used to pull OTA updates via HTTP
http_request:

# Check for firmware updates
update:
  - platform: http_request
    name: Firmware
    source: https://github.com/tntlarsn/esphome-4848s040/releases/latest/download/display.manifest.json

wifi:
  # Set up a wifi access point using the device name above
  ap:

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

# switch:  
#   - platform: restart
#     name: Restart
#     id: restart_switch

sensor:
  - platform: uptime
    id: uptime_internal
    entity_category: "diagnostic"
    device_class: "duration"
    unit_of_measurement: "s"

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dBm"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    unit_of_measurement: "dBm"
    device_class: "signal_strength"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Percentage"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: "signal_strength"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: SSID
    bssid:
      name: BSSID
    mac_address:
      name: Mac Wifi Address
    scan_results:
      name: Latest Scan Results
    dns_address:
      name: DNS Address

  # Reports the project firmware version to Home Assistant
  # This is required for the update component to detect new firmware versions
  - platform: version
    name: Firmware Version
    id: firmware_version_sensor
    entity_category: "diagnostic"
    hide_timestamp: true