globals:
  - id: ha_connected
    type: bool
    initial_value: 'false'

esphome:
  on_boot:
    # - delay: 5s
    # - lvgl.widget.hide: boot_screen
    # - delay: 30s
    # - script.execute: screen_light
    - priority: 400
      then:
        - script.execute: update_loading_page

lvgl:
  top_layer:
    widgets:
      - button:
          id: loading_page
          bg_color: color_surface_dark
          shadow_opa: transp
          width: 480
          height: 480
          widgets:
            - image:
                y: 30
                align: top_mid
                src: boot_logo

            - obj:
                id: boot_homeassistant
                y: 280
                width: 300
                height: 100
                pad_all: 0
                align: top_mid
                bg_opa: transp
                shadow_opa: transp
                border_opa: transp
                border_width: 0
                radius: 10
                widgets:
                  - label:
                      id: boot_homeassistant_label
                      align: top_mid
                      y: 0
                      text_color: color_text_dark_primary
                      text: " "
                  - spinner:
                      id: boot_homeassistant_spinner
                      width: 50
                      height: 50
                      align: bottom_mid
                      y: 0
                      spin_time: 2s
                      arc_length: 60deg
                      arc_width: 5
                      arc_color: color_primary_dark
                      indicator:
                        arc_color: color_primary
                        arc_width: 5
            - obj:
                id: boot_synchronization
                y: 280
                width: 300
                height: 60
                pad_all: 0
                align: top_mid
                bg_opa: transp
                shadow_opa: transp
                border_opa: transp
                border_width: 0
                radius: 10
                hidden: true
                widgets:
                  - label:
                      id: boot_synchronization_label
                      align: top_mid
                      y: 0
                      text_color: color_text_dark_primary
                      text: " "

                  - bar:
                      id: boot_synchronization_bar
                      y: 0
                      width: 300
                      value: 0
                      align: bottom_mid
                      min_value: 0
                      max_value: 100
                      animated: true
                      bg_color: color_primary_dark
                      indicator:
                        bg_color: color_primary


script:

  - id: update_loading_page
    then:
      - lvgl.label.update:
          id: boot_synchronization_label
          text: Synchronisierung...
      - lvgl.label.update:
          id: boot_homeassistant_label
          text: Verbindungsaufbau...

  - id: check_boot_status
    then:
      - lambda: |-
          if (id(ha_connected)) {
            lv_obj_add_flag(id(boot_homeassistant), LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(id(boot_synchronization), LV_OBJ_FLAG_HIDDEN);

            id(start_sync_animation).execute();
          }

  - id: start_sync_animation
    then:
      - delay: 1s
      - lvgl.bar.update:
          id: boot_synchronization_bar
          value: 25
          animated: true
      - delay: 1s
      - lvgl.bar.update:
          id: boot_synchronization_bar
          value: 50
          animated: true
      - delay: 1s
      - lvgl.bar.update:
          id: boot_synchronization_bar
          value: 75
          animated: true
      - delay: 1s
      - lvgl.bar.update:
          id: boot_synchronization_bar
          value: 100
          animated: true
      - delay: 1s
      - lvgl.widget.hide: loading_page


  - id: on_ha_connected
    then:
      - lambda: |-
          if (!id(ha_connected)) {
            id(ha_connected) = true;
            lv_label_set_text(id(boot_homeassistant_label), "Home Assistant Connected!");
            lv_obj_add_flag(id(boot_homeassistant_spinner), LV_OBJ_FLAG_HIDDEN);
            id(check_boot_status).execute();
          }

api:
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - script.execute: update_loading_page
          - lvgl.label.update: 
              id: ha_status
              text_color: color_primary
          - script.execute: on_ha_connected


  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - globals.set:
              id: ha_connected
              value: 'false'
          - lvgl.label.update: 
              id: ha_status
              text_color: color_primary_dark
