substitutions:
  # Home Assistant Official Color Palette
  # Source: https://design.home-assistant.io/
  # Based on Material Design & Home Assistant Frontend
  
  # Primary Colors - Home Assistant Blue
  color_primary: "0x3B82F6"        # Home Assistant Blue (Primary)
  color_primary_dark: "0x1E40AF"   # Home Assistant Blue Dark
  color_primary_light: "0x60A5FA"  # Home Assistant Blue Light
  
  # Secondary Colors
  color_secondary: "0xF59E0B"      # Amber - Secondary Action
  color_secondary_dark: "0xD97706" # Amber Dark
  
  # Status Colors
  color_success: "0x10B981"        # Green - Success/On
  color_success_dark: "0x059669"   # Green Dark
  color_warning: "0xF59E0B"        # Amber - Warning
  color_error: "0xEF4444"          # Red - Error/Off
  color_error_dark: "0xDC2626"     # Red Dark
  color_info: "0x06B6D4"           # Cyan - Info
  
  # Neutral Colors
  color_white: "0xFFFFFF"          # White
  color_black: "0x000000"          # Black
  color_gray_50: "0xF9FAFB"        # Grau 50 (sehr hell)
  color_gray_100: "0xF3F4F6"       # Grau 100
  color_gray_200: "0xE5E7EB"       # Grau 200
  color_gray_300: "0xD1D5DB"       # Grau 300
  color_gray_400: "0x9CA3AF"       # Grau 400 (medium)
  color_gray_500: "0x6B7280"       # Grau 500
  color_gray_600: "0x4B5563"       # Grau 600
  color_gray_700: "0x374151"       # Grau 700
  color_gray_800: "0x1F2937"       # Grau 800
  color_gray_900: "0x111827"       # Grau 900 (sehr dunkel)
  
  # Background Colors - Light Mode
  color_bg_light: "0xFFFFFF"       # Weißer Hintergrund
  color_bg_light_secondary: "0xF9FAFB"  # Hellgrau Hintergrund
  
  # Background Colors - Dark Mode
  color_bg_dark: "0x111827"        # Dunkler Hintergrund (Grau 900)
  color_bg_dark_secondary: "0x1F2937"   # Sekundärer dunkler Hintergrund (Grau 800)
  color_bg_dark_tertiary: "0x374151"    # Tertiärer dunkler Hintergrund (Grau 700)
  
  # Text Colors - Light Mode
  color_text_light_primary: "0x111827"   # Dunkler Text auf hellem Hintergrund
  color_text_light_secondary: "0x6B7280" # Grauer Text (sekundär)
  color_text_light_disabled: "0x9CA3AF"  # Grauer Text (deaktiviert)
  
  # Text Colors - Dark Mode
  color_text_dark_primary: "0xF9FAFB"    # Heller Text auf dunklem Hintergrund
  color_text_dark_secondary: "0xD1D5DB"  # Heller grauer Text (sekundär)
  color_text_dark_disabled: "0x9CA3AF"   # Grauer Text (deaktiviert)
  
  # Surface Colors
  color_surface: "0xFFFFFF"        # Surface (Light)
  color_surface_dark: "0x1F2937"   # Surface (Dark)
